AWSTemplateFormatVersion: '2010-09-09'
Description: AWS2022 S3 Basic

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws2022-s3-basic
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Department
          Value: AWS2022
    DeletionPolicy: Retain