AWSTemplateFormatVersion: '2010-09-09'
Description: AWS2021 IAM Role

Resources:
    WebServiceRole:
        Type: "AWS::IAM::Role"
        Properties:
            RoleName: AWS2021IAMRole
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   Effect: "Allow"
                        Principal:
                            Service:
                                - "ec2.amazonaws.com"
                        Action:
                            - "sts:AssumeRole"
            Path: "/"
            ManagedPolicyArns:
                - Fn::Sub: "arn:aws:iam::${AWS::AccountId}:policy/QytangAWSManagedPolicy"