AWSTemplateFormatVersion: '2010-09-09'
Description: AWS2022 IAM S3

Resources:
  IAMS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: aws2022-iam-s3
      WebsiteConfiguration:  # 静态网站相关配置
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:  # 公共访问阻止策略
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false #  new
        RestrictPublicBuckets: false  # any
      Tags:
        - Key: Department
          Value: AWS2022
    DeletionPolicy: Retain

  WebSiteBucketPolicy:  # 存储桶策略
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: WebSite
        Version: 2012-10-17
        Statement:
          - Sid: WebSiteAccessIndex
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref IAMS3Bucket
                - /index.html
            Condition:
              StringEquals:
                "s3:ExistingObjectTag/web_file": "http_file"

          - Sid: WebSiteAccessError
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref IAMS3Bucket
                - /error.html
            Condition:
              StringEquals:
                "s3:ExistingObjectTag/web_file": "http_file"

#          - Sid: DenyALLPut
#            Effect: Deny
#            Principal: '*'
#            Action: 's3:PutObject'
#            Resource: !Join
#              - ''
#              - - 'arn:aws:s3:::'
#                - !Ref IAMS3Bucket
#                - /*

      Bucket: !Ref IAMS3Bucket