AWSTemplateFormatVersion: "2010-09-09"
Description: Test EFS and Redis EC2
Parameters:
  KeyName: # EC2 SSH 秘钥
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    ConstraintDescription: must be the name of an existing EC2 KeyPair
    Default: us-east-1-key

  VPCStackName: # 引用之前的VPC Stack
    Type: String
    Description: Name of VPC Stack.
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPC1VPC

  SubnetStackName: # 引用Subnet Stack
    Type: String
    Description: 引用Subnet Stack
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPC2Subnets

  SecurityGroupStackName: # 引用之前的Security Group Stack
    Type: String
    Description: Name of Security Group Stack.
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPC5SecurityGroup

  EFSStackName: # 引用之前的EFS Stack
    Type: String
    Description: Name of EFS Stack.
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: EFS

Mappings:
  AWSRegionArch2AMI: # 镜像映射
    ap-northeast-2:
      HVMG2: ami-0263588f2531a56bd
    ap-southeast-2:
      HVMG2: ami-0f4484f62c4fd8767
    us-east-1:
      HVMG2: ami-061ac2e015473fbe2

Resources:
  EIP: # 申请EIP
    Type: "AWS::EC2::EIP"
    Properties:
      Tags:
        - Key: Name
          Value: EC2_EIP_2

  NetworkInterfaceEC2: # EC2网络接口
    Type: "AWS::EC2::NetworkInterface"
    Properties:
      GroupSet:
        - "Fn::ImportValue": !Sub ${SecurityGroupStackName}-EC2SecurityGroup-ID
      SubnetId:
        "Fn::ImportValue": !Sub ${SubnetStackName}-OutsideNet2-ID
      Tags:
        - Key: Name
          Value: EC2_ENI_2

  EIPAssociation: # 网络接口关联EIP
    Type: "AWS::EC2::EIPAssociation"
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      NetworkInterfaceId: !Ref NetworkInterfaceEC2

  WebServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: AWS2022WebServiceRole2
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  WebService:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: AWS2022WebServiceInstanceProfileName2
      Path: /
      Roles:
        - !Ref WebServiceRole

  EC2Instance:
    Type: "AWS::EC2::Instance"

    Properties:
      InstanceType: t3.micro  # 实例类型
      Tags: # EC2的标签
        -   Key: Name
            Value: EC2_For_EFS_Redis_Test_2
      KeyName: # EC2使用的秘钥名
        Ref: KeyName
      UserData: # EC2的UserData
        "Fn::Base64":
          "Fn::Join":
            - ""
            -   - "#!/bin/bash\n"
                - "sudo yum install -y amazon-efs-utils\n"
                - "sudo pip3 install boto3\n"
                - "sudo mkdir /efs_django\n"
                - "sudo yum install -y gcc\n"
                - "sudo wget http://download.redis.io/redis-stable.tar.gz && tar xvzf redis-stable.tar.gz && cd redis-stable && make\n"
                - "sudo sudo cp src/redis-cli /usr/bin/\n"
                - "sudo echo '"
                - "Fn::ImportValue": !Sub ${EFSStackName}-FSID
                - ":/ /efs_django efs defaults,_netdev 0 0' "
                - ">> /etc/fstab\n"
                - "\n"
      IamInstanceProfile: !Ref WebService # IAM Role
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceEC2 # 关联网络接口
          DeviceIndex: 0
      ImageId: # 找到特定Region的镜像ID
        Fn::FindInMap:
          - AWSRegionArch2AMI
          - Ref: AWS::Region
          - HVMG2
