AWSTemplateFormatVersion: "2010-09-09"
Description: Test CodeDeploy and CodePipeline EC2
Parameters:
  KeyName: # EC2 SSH 秘钥
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    ConstraintDescription: must be the name of an existing EC2 KeyPair
    Default: us-east-1-key

  VPCStackName: # 引用之前的VPC Stack
    Type: String
    Description: Name of VPC Stack.
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPC1VPC

  SubnetStackName: # 引用Subnet Stack
    Type: String
    Description: 引用Subnet Stack
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPC2Subnets

  SecurityGroupStackName: # 引用之前的Security Group Stack
    Type: String
    Description: Name of Security Group Stack.
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPC5SecurityGroup

Mappings:
  AWSRegionArch2AMI: # 镜像映射
    ap-northeast-2:
      HVMG2: ami-0263588f2531a56bd
    ap-southeast-2:
      HVMG2: ami-0f4484f62c4fd8767
    us-east-1:
      HVMG2: ami-061ac2e015473fbe2

Resources:
  NetworkInterfaceEC21: # EC2网络接口
    Type: "AWS::EC2::NetworkInterface"
    Properties:
      GroupSet:
        - "Fn::ImportValue": !Sub ${SecurityGroupStackName}-EC2SecurityGroup-ID
      SubnetId:
        "Fn::ImportValue": !Sub ${SubnetStackName}-InsideNet1-ID
      Tags:
        - Key: Name
          Value: EC2_ENI_1

  NetworkInterfaceEC22: # EC2网络接口
    Type: "AWS::EC2::NetworkInterface"
    Properties:
      GroupSet:
        - "Fn::ImportValue": !Sub ${SecurityGroupStackName}-EC2SecurityGroup-ID
      SubnetId:
        "Fn::ImportValue": !Sub ${SubnetStackName}-InsideNet2-ID
      Tags:
        - Key: Name
          Value: EC2_ENI_2

  WebServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: AWS2022WebServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  WebService:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: AWS2022WebServiceInstanceProfileName
      Path: /
      Roles:
        - !Ref WebServiceRole

  EC2Instance1:
    Type: "AWS::EC2::Instance"

    Properties:
      InstanceType: t3.micro  # 实例类型
      Tags: # EC2的标签
        -   Key: AWS2022
            Value: EC2_For_LoadBalance
        -   Key: Name
            Value: LB_EC2_1
      KeyName: # EC2使用的秘钥名
        Ref: KeyName
      UserData: # EC2的UserData
        "Fn::Base64":
          "Fn::Join":
            - ""
            -   - "#!/bin/bash\n"
                - "sudo yum install -y ruby\n"
                - "sudo aws s3 cp s3://aws-codedeploy-us-east-1/latest/install . --region us-east-1\n"
                - "sudo chmod +x install\n"
                - "sudo ./install auto\n"
                - "\n"
      IamInstanceProfile: !Ref WebService # IAM Role
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceEC21 # 关联网络接口
          DeviceIndex: 0
      ImageId: # 找到特定Region的镜像ID
        Fn::FindInMap:
          - AWSRegionArch2AMI
          - Ref: AWS::Region
          - HVMG2

  EC2Instance2:
    Type: "AWS::EC2::Instance"

    Properties:
      InstanceType: t3.micro  # 实例类型
      Tags: # EC2的标签
        - Key: AWS2022
          Value: EC2_For_LoadBalance
        - Key: Name
          Value: LB_EC2_2
      KeyName: # EC2使用的秘钥名
        Ref: KeyName
      UserData: # EC2的UserData
        "Fn::Base64":
          "Fn::Join":
            - ""
            - - "#!/bin/bash\n"
              - "sudo yum install -y ruby\n"
              - "sudo aws s3 cp s3://aws-codedeploy-us-east-1/latest/install . --region us-east-1\n"
              - "sudo chmod +x install\n"
              - "sudo ./install auto\n"
              - "\n"
      IamInstanceProfile: !Ref WebService # IAM Role
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterfaceEC22 # 关联网络接口
          DeviceIndex: 0
      ImageId: # 找到特定Region的镜像ID
        Fn::FindInMap:
          - AWSRegionArch2AMI
          - Ref: AWS::Region
          - HVMG2

Outputs:
    InstanceId1: # 输出EC2的实例ID
        Description: InstanceId of Load Balance EC1
        Value: !Ref EC2Instance1
        Export:
          Name: !Sub ${AWS::StackName}-InstanceId1

    InstanceId2: # 输出EC2的实例ID
      Description: InstanceId of Load Balance EC2
      Value: !Ref EC2Instance2
      Export:
        Name: !Sub ${AWS::StackName}-InstanceId2
