AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KeyName: # EC2 SSH 秘钥
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    ConstraintDescription: must be the name of an existing EC2 KeyPair
    Default: us-east-1-key

  VPCStackName: # 引用之前的VPC Stack
    Type: String
    Description: Name of VPC Stack.
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPC1VPC

  SubnetStackName: # 引用Subnet Stack
    Type: String
    Description: 引用Subnet Stack
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPC2Subnets

  SecurityGroupStackName: # 引用之前的Security Group Stack
    Type: String
    Description: Name of Security Group Stack.
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: VPC5SecurityGroup

Mappings:
  AWSRegionArch2AMI: # 镜像映射
    ap-northeast-2:
      HVMG2: ami-0263588f2531a56bd
    ap-southeast-2:
      HVMG2: ami-0f4484f62c4fd8767
    us-east-1:
      HVMG2: ami-061ac2e015473fbe2

Resources:
  WebServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: AWS2022LaunchTemplateRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess

  WebService:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: AWS2022LaunchTemplateInstanceProfileName
      Path: /
      Roles:
        - !Ref WebServiceRole
  QYTLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: QYTAWS2022LaunchTemplate
      LaunchTemplateData:
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: LaunchTemplateEC2
              - Key: AWS2022
                Value: EC2_For_LoadBalance
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: false
            Groups:
              - "Fn::ImportValue": !Sub ${SecurityGroupStackName}-EC2SecurityGroup-ID
            DeleteOnTermination: true
        Placement:
          Tenancy: default
        IamInstanceProfile:
          Name: !Ref WebService # IAM Role
        ImageId: # 找到特定Region的镜像ID
          Fn::FindInMap:
            - AWSRegionArch2AMI
            - Ref: AWS::Region
            - HVMG2
        InstanceType: t3.micro
        KeyName: !Ref KeyName
        UserData: # EC2的UserData
          "Fn::Base64":
            "Fn::Join":
              - ""
              - - "#!/bin/bash\n"
                - "sudo yum install -y ruby\n"
                - "sudo aws s3 cp s3://aws-codedeploy-us-east-1/latest/install . --region us-east-1\n"
                - "sudo chmod +x install\n"
                - "sudo ./install auto\n"
                - "\n"

Outputs:
    LaunchTemplate: # 输出EC2的实例ID
        Description: AWS2022 LaunchTemplate
        Value: !Ref QYTLaunchTemplate
        Export:
          Name: !Sub ${AWS::StackName}-LaunchTemplate

    LaunchTemplateLatestVersionNumber: # 输出EC2的实例ID
      Description: AWS2022 LaunchTemplate Latest Version Number
      Value:
        Fn::GetAtt: ["QYTLaunchTemplate", "LatestVersionNumber"]
      Export:
        Name: !Sub ${AWS::StackName}-LaunchTemplateLatestVersionNumber