AWSTemplateFormatVersion: 2010-09-09
Description: Full EC2
Parameters:
    KeyName: # EC2 SSH 秘钥
        Type: AWS::EC2::KeyPair::KeyName
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
        ConstraintDescription: must be the name of an existing EC2 KeyPair
        Default: us-east-1-key

    NetworkStackName: # 引用之前的Stack
        Type: String
        Description: Name of an active CloudFormation stack that contains the networking resources, such as the subnet and security group, that will be used in this stack.
        MinLength: 1
        MaxLength: 255
        AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
        Default: EC2VPC

Mappings:
    AWSRegionArch2AMI: # 镜像映射
        ap-northeast-2:
            HVMG2: ami-0263588f2531a56bd
        ap-southeast-2:
            HVMG2: ami-0f4484f62c4fd8767
        us-east-1:
            HVMG2: ami-061ac2e015473fbe2

Resources:
    WebServiceRole:
        Type: "AWS::IAM::Role"
        Properties:
            RoleName: AWS2022WebServiceRole
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   Effect: "Allow"
                        Principal:
                            Service:
                                - "ec2.amazonaws.com"
                        Action:
                            - "sts:AssumeRole"
            Path: "/"
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
                - arn:aws:iam::aws:policy/AmazonS3FullAccess
                - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
                - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
                - arn:aws:iam::aws:policy/AmazonSSMFullAccess

    WebService:
        Type: "AWS::IAM::InstanceProfile"
        Properties:
            InstanceProfileName: AWS2022WebServiceInstanceProfileName
            Path: /
            Roles:
                - !Ref WebServiceRole

    PlacementGroup:
        Type: AWS::EC2::PlacementGroup
        Properties:
            Strategy: spread  # cluster | partition | spread

    EC2Instance:
        Type: "AWS::EC2::Instance"

        Properties:
            InstanceType: t3.micro  # 实例类型
            Tenancy: default  # Allowed values: dedicated | default | host
            PlacementGroupName: !Ref PlacementGroup
            Tags: # EC2的标签
                -   Key: Name
                    Value: EC2Full
            KeyName: # EC2使用的秘钥名
                Ref: KeyName
            UserData: # EC2的UserData
                "Fn::Base64":
                    "Fn::Join":
                        - ""
                        -   - "#!/bin/bash\n"
                            - "sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config\n"
                            - "sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config\n"
                            - "sudo sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config\n"
                            - "sh -c 'echo root:Cisc0123' | sudo chpasswd\n"
                            - "sudo service sshd restart\n"
                            - "\n"
            IamInstanceProfile: !Ref WebService # IAM Role
            NetworkInterfaces:
                - NetworkInterfaceId: !Ref NetworkInterface # 关联网络接口
                  DeviceIndex: 0
            ImageId: # 找到特定Region的镜像ID
                Fn::FindInMap:
                    - AWSRegionArch2AMI
                    - Ref: AWS::Region
                    - HVMG2

    NetworkInterface: # EC2调用的网络接口
        Type: "AWS::EC2::NetworkInterface"
        Properties:
            GroupSet: # 关联SecurityGroup
                - "Fn::ImportValue": !Sub ${NetworkStackName}-EC2SecurityGroup-ID
            SubnetId: # 关联子网
                "Fn::ImportValue": !Sub ${NetworkStackName}-EC2Net1-ID

Outputs:
    InstanceId: # 输出EC2的实例ID
        Description: InstanceId of the newly created EC2 instance
        Value: !Ref EC2Instance

    AZ: # 输出EC2的可用区域
        Description: Availability Zone of the newly created EC2 instance
        Value: !GetAtt EC2Instance.AvailabilityZone

    PublicIP: # 输出EC2的公网IP
        Description: Public IP address of the newly created EC2 instance
        Value: !GetAtt EC2Instance.PublicIp