AWSTemplateFormatVersion: 2010-09-09
Description: Create IAM Role For GUI

Resources:
  EKSRole:  # 集群角色
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: QYTEKSClusterRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSClusterPolicy'
        - 'arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'  # 下载镜像权限 https://aws.amazon.com/premiumsupport/knowledge-center/eks-ecr-troubleshooting/
        - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  NodeRole:  # 节点角色
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: QYTEKSNodeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'   # 下载镜像权限 https://aws.amazon.com/premiumsupport/knowledge-center/eks-ecr-troubleshooting/
        - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
