AWSTemplateFormatVersion: 2010-09-09
Description: Route53 A record

Parameters:
  EC2StackName: # 引用EC2 Stack
    Type: String
    Description: 引用USE EC2 Stack
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: Route53EC2USE

Resources:
  myDNSRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: Z1JOS2YODO11W5
      Comment: API Server Domian Name
      Name: weighted.mingjiao.org.
      HealthCheckId: !Ref myHealthCheck
      Weight: 75
      Type: A
      TTL: 30
      SetIdentifier: 2
      ResourceRecords:
        - Fn::ImportValue: !Sub ${EC2StackName}-EC2-IP

  myHealthCheck:
    Type: 'AWS::Route53::HealthCheck'
    Properties:
      HealthCheckConfig:
        IPAddress:
          Fn::ImportValue: !Sub ${EC2StackName}-EC2-IP
        Port: 80
        Type: HTTP
        ResourcePath: '/staff_info'
        FullyQualifiedDomainName: 'weighted.mingjiao.org'
        RequestInterval: 30
        FailureThreshold: 3
      HealthCheckTags:
        - Key: Department
          Value: AWS2022
        - Key: Location
          Value: US EAST 1