AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC Subnets

Parameters:
    VPCStackName: # 引用VPC Stack
        Type: String
        Description: 引用VPC Stack
        MinLength: 1
        MaxLength: 255
        AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
        Default: VPC1VPC

Resources:
  # 网络InsideNet1
  InsideNet1:
    Type: "AWS::EC2::Subnet"
    DeletionPolicy: Delete
    Properties:
      AvailabilityZone: # 选择第一个（0）AZ
        "Fn::Select":
          - 0
          - "Fn::GetAZs": ""
      CidrBlock: 10.1.101.0/24
#      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Inside-Net-1
      VpcId:
        Fn::ImportValue: !Sub ${VPCStackName}-VPCID

  # 网络InsideNet2
  InsideNet2:
    Type: "AWS::EC2::Subnet"
    DeletionPolicy: Delete
    Properties:
      AvailabilityZone: # 选择第一个（0）AZ
        "Fn::Select":
          - 2
          - "Fn::GetAZs": ""
      CidrBlock: 10.1.102.0/24
      #      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Inside-Net-2
      VpcId:
        Fn::ImportValue: !Sub ${VPCStackName}-VPCID

  # 网络OutsideNet1
  OutsideNet1:
    Type: "AWS::EC2::Subnet"
    DeletionPolicy: Delete
    Properties:
      AvailabilityZone: # 选择第一个（0）AZ
        "Fn::Select":
          - 0
          - "Fn::GetAZs": ""
      CidrBlock: 10.1.11.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Outside-Net-1
      VpcId:
        Fn::ImportValue: !Sub ${VPCStackName}-VPCID

  # 网络OutsideNet2
  OutsideNet2:
    Type: "AWS::EC2::Subnet"
    DeletionPolicy: Delete
    Properties:
      AvailabilityZone: # 选择第一个（0）AZ
        "Fn::Select":
          - 2
          - "Fn::GetAZs": ""
      CidrBlock: 10.1.12.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Outside-Net-2
      VpcId:
        Fn::ImportValue: !Sub ${VPCStackName}-VPCID

  # 网络PrivateNet1
  PrivateNet1:
    Type: "AWS::EC2::Subnet"
    DeletionPolicy: Delete
    Properties:
      AvailabilityZone: # 选择第一个（0）AZ
        "Fn::Select":
          - 0
          - "Fn::GetAZs": ""
      CidrBlock: 10.1.201.0/24
      #      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Private-Net-1
      VpcId:
        Fn::ImportValue: !Sub ${VPCStackName}-VPCID

  # 网络PrivateNet2
  PrivateNet2:
    Type: "AWS::EC2::Subnet"
    DeletionPolicy: Delete
    Properties:
      AvailabilityZone: # 选择第一个（0）AZ
        "Fn::Select":
          - 2
          - "Fn::GetAZs": ""
      CidrBlock: 10.1.202.0/24
      #      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Private-Net-2
      VpcId:
        Fn::ImportValue: !Sub ${VPCStackName}-VPCID

Outputs: # 输出内容，并且可以被其他Stack引用
    InsideNet1:
        Description: The subnet ID of InsideNet1
        Value: !Ref InsideNet1
        Export:
            Name: !Sub ${AWS::StackName}-InsideNet1-ID

    InsideNet2:
        Description: The subnet ID of InsideNet2
        Value: !Ref InsideNet2
        Export:
            Name: !Sub ${AWS::StackName}-InsideNet2-ID

    OutsideNet1:
        Description: The subnet ID of OutsideNet1
        Value: !Ref OutsideNet1
        Export:
            Name: !Sub ${AWS::StackName}-OutsideNet1-ID

    OutsideNet2:
        Description: The subnet ID of OutsideNet2
        Value: !Ref OutsideNet2
        Export:
            Name: !Sub ${AWS::StackName}-OutsideNet2-ID

    PrivateNet1:
        Description: The subnet ID of PrivateNet1
        Value: !Ref PrivateNet1
        Export:
            Name: !Sub ${AWS::StackName}-PrivateNet1-ID

    PrivateNet2:
        Description: The subnet ID of PrivateNet2
        Value: !Ref PrivateNet2
        Export:
            Name: !Sub ${AWS::StackName}-PrivateNet2-ID