AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC Internet Gateway

Parameters:
    VPCStackName: # 引用VPC Stack
        Type: String
        Description: 引用VPC Stack
        MinLength: 1
        MaxLength: 255
        AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
        Default: VPC1VPC

Resources:
  # Internet网关
  InternetGW:
      Type: "AWS::EC2::InternetGateway"
      DeletionPolicy: Delete
      Properties:
          Tags:
              - Key: Name
                Value: InternetGW

  # 关联Internet GW到VPC
  AttachGW:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId:
        Fn::ImportValue: !Sub ${VPCStackName}-VPCID
      InternetGatewayId: !Ref InternetGW

Outputs: # 输出内容，并且可以被其他Stack引用
    InternetGW:
        Description: The subnet ID of InsideNet1
        Value: !Ref InternetGW
        Export:
            Name: !Sub ${AWS::StackName}-InternetGW-ID