AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC

Resources:
  QYTVPC:  # 创建VPC
    Type: AWS::EC2::VPC
    DeletionPolicy: Delete
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: QYT_VPC

  VPCCidr:  # Secondary CIDR
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      CidrBlock: 137.78.0.0/16
      VpcId: !Ref QYTVPC

  VPCDHCPOption:  # VPC DHCP选项
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: qytang.com
      # DHCP选项介绍 https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html
      DomainNameServers:
        - 169.254.169.253
        - 114.114.114.114
      NtpServers:
        - 169.254.169.123

  VPCDHCPAssociation:  # 关联DHCP选项到VPC
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      DhcpOptionsId: !Ref VPCDHCPOption
      VpcId: !Ref QYTVPC

Outputs: # 输出内容，并且可以被其他Stack引用
    # VPCID, 输出名为${AWS::StackName}-VPCID
    VPCId:
        Description: VPC ID
        Value: !Ref QYTVPC
        Export:
            Name: !Sub ${AWS::StackName}-VPCID